# Based on https://github.com/CleanroomMC/GroovyScript/blob/63da27acb345aa7af3b8af583cf4c185e0254711/.github/workflows/build.yaml
# This workflow must be manually triggered. It accepts a version and a release type.
# First it sets the version in gradle.properties to the new version and pushes it.
# Then it generates a log, based on commits.
# After that builds a jar and uploads it to curseforge/modrinth/GitHub releases

name: Build, Publish and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Mod version'
        required: true
      tags:
        type: choice
        description: Release tags
        options:
          - Alpha
          - Beta
          - Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Check if tag already exists
        run: |
          if git rev-parse --verify --quiet "${{ github.event.inputs.version }}"; then
            echo "Version ${{ github.event.inputs.version }} already exists, aborting workflow."
            exit 1
          fi

      - name: Set version
        run: sed -i "s/version.*=.*/version = '${{ github.event.inputs.version }}'/g" build.gradle

      - name: Commit and push build.gradle
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Bump version to ${{ github.event.inputs.version }}"
          commit_options: "--no-verify"
          file_pattern: build.gradle
          tagging_message: "${{ github.event.inputs.version }}"

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle # Only cache stuff since test build action happen mostly

      - name: Publish to maven
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish # Included build task for required artifact
        
      - name: Create simple tags case changer
        id: release_tag
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.event.inputs.tags }}

      - name: Publish Minecraft Mods
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: 419286
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          files: |
            build/libs/!(*-@(dev|sources|javadoc)).jar
            build/libs/*-@(sources).jar
            build/libs/*-@(dev).jar
          name: ${{ github.event.inputs.version }}
          version: ${{ github.event.inputs.version }}
          version-type: ${{ steps.release_tag.outputs.lowercase }}
          loaders: forge
          game-versions: |
            [1.8,1.12.2]
          game-version-filter: releases | snapshots
          java: 8
          retry-attempts: 2
